services:
  rule-api:
    build: .
    container_name: bun-pdf-api
    env_file: .env
    networks:
      - npm-network
    volumes:
      - ./data:/data
    restart: unless-stopped

networks:
  npm-network:
    external: true
